# Generated by Django 2.0.1 on 2018-01-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PiOperate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCILIST',
            new_name='Applist',
        ),
    ]
